// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tsPoint.proto

package storage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WPoint struct {
	DataBase             string            `protobuf:"bytes,1,opt,name=dataBase,proto3" json:"dataBase,omitempty"`
	TableName            string            `protobuf:"bytes,2,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Value                map[string]*Value `protobuf:"bytes,4,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WPoint) Reset()         { *m = WPoint{} }
func (m *WPoint) String() string { return proto.CompactTextString(m) }
func (*WPoint) ProtoMessage()    {}
func (*WPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_c26f73b6b2d6de33, []int{0}
}

func (m *WPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WPoint.Unmarshal(m, b)
}
func (m *WPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WPoint.Marshal(b, m, deterministic)
}
func (m *WPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WPoint.Merge(m, src)
}
func (m *WPoint) XXX_Size() int {
	return xxx_messageInfo_WPoint.Size(m)
}
func (m *WPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_WPoint.DiscardUnknown(m)
}

var xxx_messageInfo_WPoint proto.InternalMessageInfo

func (m *WPoint) GetDataBase() string {
	if m != nil {
		return m.DataBase
	}
	return ""
}

func (m *WPoint) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *WPoint) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *WPoint) GetValue() map[string]*Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Value struct {
	Kv                   map[int64][]byte `protobuf:"bytes,1,rep,name=kv,proto3" json:"kv,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_c26f73b6b2d6de33, []int{1}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetKv() map[int64][]byte {
	if m != nil {
		return m.Kv
	}
	return nil
}

type RPoint struct {
	Rp                   map[string]*Value `protobuf:"bytes,1,rep,name=rp,proto3" json:"rp,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RPoint) Reset()         { *m = RPoint{} }
func (m *RPoint) String() string { return proto.CompactTextString(m) }
func (*RPoint) ProtoMessage()    {}
func (*RPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_c26f73b6b2d6de33, []int{2}
}

func (m *RPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPoint.Unmarshal(m, b)
}
func (m *RPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPoint.Marshal(b, m, deterministic)
}
func (m *RPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPoint.Merge(m, src)
}
func (m *RPoint) XXX_Size() int {
	return xxx_messageInfo_RPoint.Size(m)
}
func (m *RPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_RPoint.DiscardUnknown(m)
}

var xxx_messageInfo_RPoint proto.InternalMessageInfo

func (m *RPoint) GetRp() map[string]*Value {
	if m != nil {
		return m.Rp
	}
	return nil
}

func init() {
	proto.RegisterType((*WPoint)(nil), "storage.wPoint")
	proto.RegisterMapType((map[string]string)(nil), "storage.wPoint.TagsEntry")
	proto.RegisterMapType((map[string]*Value)(nil), "storage.wPoint.ValueEntry")
	proto.RegisterType((*Value)(nil), "storage.value")
	proto.RegisterMapType((map[int64][]byte)(nil), "storage.value.KvEntry")
	proto.RegisterType((*RPoint)(nil), "storage.rPoint")
	proto.RegisterMapType((map[string]*Value)(nil), "storage.rPoint.RpEntry")
}

func init() { proto.RegisterFile("tsPoint.proto", fileDescriptor_c26f73b6b2d6de33) }

var fileDescriptor_c26f73b6b2d6de33 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0xa5, 0xe9, 0x6c, 0xed, 0x37, 0x15, 0x09, 0xa2, 0x31, 0x78, 0x18, 0x43, 0x74, 0x17, 0x83,
	0x4c, 0x44, 0xf1, 0x28, 0x0c, 0x04, 0x41, 0xa4, 0x88, 0xf7, 0x6f, 0x18, 0x8b, 0x74, 0xae, 0x25,
	0x89, 0xd5, 0xfd, 0x21, 0x7f, 0xa7, 0x2c, 0x89, 0x5d, 0x94, 0xde, 0x76, 0xcb, 0xfb, 0xde, 0xfb,
	0xde, 0x7b, 0x21, 0x81, 0x6d, 0xa3, 0x1f, 0xab, 0xb7, 0xb9, 0x11, 0xb5, 0xaa, 0x4c, 0x45, 0x53,
	0x6d, 0x2a, 0x85, 0x85, 0x1c, 0x7e, 0x13, 0x48, 0x3e, 0x2d, 0x43, 0x39, 0x6c, 0xbe, 0xa0, 0xc1,
	0x5b, 0xd4, 0x92, 0x45, 0x83, 0x68, 0x94, 0xe5, 0x2d, 0xa6, 0x47, 0x90, 0x19, 0x9c, 0xce, 0xe4,
	0x03, 0xbe, 0x4b, 0x46, 0x2c, 0xb9, 0x1a, 0xd0, 0x33, 0xe8, 0x19, 0x2c, 0x34, 0x8b, 0x07, 0xf1,
	0xa8, 0x3f, 0x3e, 0x14, 0xde, 0x5c, 0x38, 0x63, 0xf1, 0x84, 0x85, 0x9e, 0xcc, 0x8d, 0x5a, 0xe4,
	0x56, 0x46, 0xcf, 0x61, 0xa3, 0xc1, 0xd9, 0x87, 0x64, 0x3d, 0xab, 0xe7, 0xff, 0xf5, 0xcf, 0x4b,
	0xd2, 0x2d, 0x38, 0x21, 0xbf, 0x82, 0xac, 0x35, 0xa1, 0xbb, 0x10, 0x97, 0x72, 0xe1, 0x2b, 0x2e,
	0x8f, 0x74, 0xef, 0xd7, 0xd0, 0x35, 0x73, 0xe0, 0x86, 0x5c, 0x47, 0xfc, 0x0e, 0x60, 0xe5, 0xd6,
	0xb1, 0x79, 0x1c, 0x6e, 0xf6, 0xc7, 0x3b, 0x6d, 0x15, 0x3b, 0x0d, 0x9c, 0x86, 0xaf, 0x5e, 0x49,
	0x4f, 0x80, 0x94, 0x0d, 0x8b, 0x6c, 0xf5, 0xfd, 0xbf, 0x7a, 0x71, 0xdf, 0xb8, 0xda, 0xa4, 0x6c,
	0xf8, 0x25, 0xa4, 0x1e, 0x86, 0xb9, 0x71, 0x47, 0xe3, 0xad, 0x30, 0xe7, 0x0b, 0x12, 0xe5, 0xde,
	0xe3, 0x14, 0x88, 0xaa, 0x7d, 0xd0, 0x41, 0x1b, 0xe4, 0x48, 0x91, 0xd7, 0x3e, 0x49, 0xd5, 0x7c,
	0x02, 0xa9, 0x87, 0xeb, 0xdc, 0x70, 0x9a, 0xd8, 0xaf, 0x71, 0xf1, 0x13, 0x00, 0x00, 0xff, 0xff,
	0x2e, 0xa1, 0x9b, 0xc8, 0x2b, 0x02, 0x00, 0x00,
}
