// Code generated by protoc-gen-go. DO NOT EDIT.
// source: getCmd.proto

package cmd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetCmd struct {
	DataBase             string            `protobuf:"bytes,1,opt,name=dataBase,proto3" json:"dataBase,omitempty"`
	TableName            string            `protobuf:"bytes,2,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	FieldKey             string            `protobuf:"bytes,4,opt,name=fieldKey,proto3" json:"fieldKey,omitempty"`
	StartTime            int64             `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int64             `protobuf:"varint,6,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetCmd) Reset()         { *m = GetCmd{} }
func (m *GetCmd) String() string { return proto.CompactTextString(m) }
func (*GetCmd) ProtoMessage()    {}
func (*GetCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_58674a2f36386284, []int{0}
}

func (m *GetCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCmd.Unmarshal(m, b)
}
func (m *GetCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCmd.Marshal(b, m, deterministic)
}
func (m *GetCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCmd.Merge(m, src)
}
func (m *GetCmd) XXX_Size() int {
	return xxx_messageInfo_GetCmd.Size(m)
}
func (m *GetCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCmd.DiscardUnknown(m)
}

var xxx_messageInfo_GetCmd proto.InternalMessageInfo

func (m *GetCmd) GetDataBase() string {
	if m != nil {
		return m.DataBase
	}
	return ""
}

func (m *GetCmd) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *GetCmd) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *GetCmd) GetFieldKey() string {
	if m != nil {
		return m.FieldKey
	}
	return ""
}

func (m *GetCmd) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GetCmd) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func init() {
	proto.RegisterType((*GetCmd)(nil), "cmd.getCmd")
	proto.RegisterMapType((map[string]string)(nil), "cmd.getCmd.TagsEntry")
}

func init() { proto.RegisterFile("getCmd.proto", fileDescriptor_58674a2f36386284) }

var fileDescriptor_58674a2f36386284 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x4f, 0x2d, 0x71,
	0xce, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0xce, 0x4d, 0x51, 0xfa, 0xc5,
	0xc8, 0xc5, 0x06, 0x11, 0x15, 0x92, 0xe2, 0xe2, 0x48, 0x49, 0x2c, 0x49, 0x74, 0x4a, 0x2c, 0x4e,
	0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x85, 0x64, 0xb8, 0x38, 0x4b, 0x12, 0x93,
	0x72, 0x52, 0xfd, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0, 0x92, 0x08, 0x01, 0x21, 0x4d, 0x2e, 0x96,
	0x92, 0xc4, 0xf4, 0x62, 0x09, 0x66, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x51, 0xbd, 0xe4, 0xdc, 0x14,
	0x3d, 0xa8, 0x55, 0x21, 0x89, 0xe9, 0xc5, 0xae, 0x79, 0x25, 0x45, 0x95, 0x41, 0x60, 0x25, 0x20,
	0x4b, 0xd2, 0x32, 0x53, 0x73, 0x52, 0xbc, 0x53, 0x2b, 0x25, 0x58, 0x20, 0x96, 0xc0, 0xf8, 0x20,
	0x4b, 0x8a, 0x4b, 0x12, 0x8b, 0x4a, 0x42, 0x32, 0x73, 0x53, 0x25, 0x58, 0x15, 0x18, 0x35, 0x98,
	0x83, 0x10, 0x02, 0x42, 0x12, 0x5c, 0xec, 0xa9, 0x79, 0x29, 0x60, 0x39, 0x36, 0xb0, 0x1c, 0x8c,
	0x2b, 0x65, 0xce, 0xc5, 0x09, 0xb7, 0x46, 0x48, 0x80, 0x8b, 0x39, 0x3b, 0xb5, 0x12, 0xea, 0x01,
	0x10, 0x53, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x14, 0xe6, 0x6e, 0x08, 0xc7, 0x8a, 0xc9,
	0x82, 0x31, 0x89, 0x0d, 0x1c, 0x10, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x8b, 0x83,
	0x0f, 0x18, 0x01, 0x00, 0x00,
}
